### ISSUE TITLE
Redis::expire() expects parameter 2 to be integer, string give @ M1.9.4.x. and PHP 7.2

### ISSUE THREAD

**Issue by seansan** [colinmollenhour/credis#109] opened 2019-02-15 15:16 UTC
Redis::expire() expects parameter 2 to be integer, string give @ M1.9.4.x. and PHP 7.2

Error in logging:
Warning: Redis::expire() expects parameter 2 to be integer, string given  in /var/www/html/shirts/public_html/app/code/local/Credis/Client.php on line 114

I remember we did/kinda tackled this before .. but now it is back dont know yet how or why. And not sure if this is related to credis or the method storing the data

**Comment by colinmollenhour** [comment] 2023-01-27 06:35
Duplicate of #103

**Closed by colinmollenhour** 2023-01-27 06:35 UTC
